[General]
bIsDebug = false

[Image]
bDrawKeyBackground = 0

[Font]
bLoad = true
sName = DrukaatieBurti-Regular.ttf
fSize = 20
bChineseFull = 0
bChineseSimplifiedCommon = 0
bCyrillic = 0
bJapanese = 0
bKorean = 0
bThai = 0
bVietnamese = 0

[Config]
sDefault = LamasTinyHUD_Custom.ini
sElden = LamasTinyHUD_Custom_Elden.ini
