# Global scaling factor: the whole hud size changes when you change this.
global_scale = 1.0
# Enable to turn on debug logging. Requires a restart.
debug = false
# Typeface to use. Must be truetype. Must be in resources/fonts.
font = "futura-book-bt.ttf"
# Point size to use for all name text. Scales with the global_scale.
font_size = 20.0
# unused right now
animation_alpha = 51
# unused right now
animation_duration = 0.2
# Enable any of these you need text rendering for.
chinese_full_glyphs = false
simplified_chinese_glyphs = true
cyrillic_glyphs = true
japanese_glyphs = false
korean_glyphs = false
thai_glyphs = false
vietnamese_glyphs = false

# A named location for the HUD. Use this as a shortcut for common anchor
# points. These work no matter what the player's screen resolution is, because this
# is turned into a location point at run-time.
# Values: bottom_left, bottom_right, top_left, top_right, center
anchor_point = "bottom_left"
# You can also specify the anchor point like this if a named anchor point
# doesn't work for your layout. These values are NOT scaled.
#anchor = { x = 150.0, y = 1375.0 }
# The size of the hud, before the global scaling factor is applied.
size = { x = 300.0, y = 250.0 }

# The color of the HUD background file. Set to 0 to skip.
[bg_color]
r = 0
g = 0
b = 0
a = 0

[[layouts]]
name = "Shouts/Powers"
count_font_size = 15.0

[layouts.element]
repr = 0

[layouts.offset]
x = -110.0
y = 0.0

[layouts.size]
x = 75.0
y = 75.0

[layouts.bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.icon_color]
r = 200
g = 200
b = 200
a = 255

[layouts.icon_size]
x = 50.0
y = 50.0

[layouts.hotkey_color]
r = 255
g = 255
b = 255
a = 0

[layouts.hotkey_offset]
x = 50.0
y = 0.0

[layouts.hotkey_size]
x = 30.0
y = 30.0

[layouts.hotkey_bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.count_offset]
x = 0.0
y = 0.0

[layouts.count_color]
r = 255
g = 255
b = 255
a = 0

[layouts.name_color]
r = 255
g = 255
b = 255
a = 0

[layouts.name_offset]
x = -25.0
y = 50.0

[[layouts]]
name = "Consumables"
count_font_size = 20.0

[layouts.element]
repr = 1

[layouts.offset]
x = -110.0
y = -75.0

[layouts.size]
x = 75.0
y = 75.0

[layouts.bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.icon_color]
r = 255
g = 255
b = 255
a = 255

[layouts.icon_size]
x = 50.0
y = 50.0

[layouts.hotkey_color]
r = 255
g = 255
b = 255
a = 0

[layouts.hotkey_offset]
x = 50.0
y = 0.0

[layouts.hotkey_size]
x = 30.0
y = 30.0

[layouts.hotkey_bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.count_offset]
x = 30.0
y = 7.0

[layouts.count_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_color]
r = 255
g = 255
b = 255
a = 0

[layouts.name_offset]
x = 150.0
y = -38.0

[[layouts]]
name = "Left Hand"
count_font_size = 20.0

[layouts.element]
repr = 2

[layouts.offset]
x = -35.0
y = 0.0

[layouts.size]
x = 75.0
y = 75.0

[layouts.bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.icon_color]
r = 255
g = 255
b = 255
a = 255

[layouts.icon_size]
x = 50.0
y = 50.0

[layouts.hotkey_color]
r = 255
g = 255
b = 255
a = 0

[layouts.hotkey_offset]
x = 50.0
y = 0.0

[layouts.hotkey_size]
x = 30.0
y = 30.0

[layouts.hotkey_bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.count_offset]
x = 0.0
y = 0.0

[layouts.count_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_color]
r = 255
g = 255
b = 255
a = 0

[layouts.name_offset]
x = -125.0
y = 75.0

[[layouts]]
name = "Right Hand"
count_font_size = 20.0

[layouts.element]
repr = 3

[layouts.offset]
x = 40.0
y = 0.0

[layouts.size]
x = 75.0
y = 75.0

[layouts.bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.icon_color]
r = 255
g = 255
b = 255
a = 255

[layouts.icon_size]
x = 50.0
y = 50.0

[layouts.hotkey_color]
r = 255
g = 255
b = 255
a = 0

[layouts.hotkey_offset]
x = 50.0
y = 0.0

[layouts.hotkey_size]
x = 30.0
y = 30.0

[layouts.hotkey_bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.count_offset]
x = 0.0
y = 0.0

[layouts.count_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_color]
r = 255
g = 255
b = 255
a = 0

[layouts.name_offset]
x = -225.0
y = 100.0

[[layouts]]
name = "Ammo"
count_font_size = 20.0

[layouts.element]
repr = 4

[layouts.offset]
x = -35.0
y = -72.0

[layouts.size]
x = 75.0
y = 75.0

[layouts.bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.icon_color]
r = 255
g = 255
b = 255
a = 255

[layouts.icon_size]
x = 50.0
y = 50.0

[layouts.hotkey_color]
r = 255
g = 255
b = 255
a = 0

[layouts.hotkey_offset]
x = 50.0
y = 0.0

[layouts.hotkey_size]
x = 20.0
y = 20.0

[layouts.hotkey_bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.count_offset]
x = 30.0
y = 7.0

[layouts.count_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_color]
r = 255
g = 255
b = 255
a = 0

[layouts.name_offset]
x = 50.0
y = -13.0
